export const ANIMATION = {
  SCREEN_TRANSITION_MS: 280,
  BANNER_TRANSITION_MS: 220,
  STAT_BAR_FILL_MS: 700,
  SKELETON_PULSE_MS: 750,
  SKELETON_MIN_OPACITY: 0.45,
  PRESSED_SCALE: 0.97,
  PRESSED_OPACITY: 0.85,
} as const;
