export const FORMAT = {
  POKEDEX_NUMBER_PREFIX: '#',
  POKEDEX_NUMBER_DIGITS: 4,
  POKEDEX_NUMBER_PAD: '0',
  MEASUREMENT_DECIMALS: 1,
  NAME_SEPARATOR: '-',
  WORD_SEPARATOR: ' ',
  LIST_SEPARATOR: ', ',
} as const;
