export const LAYOUT = {
  CONTENT_MAX_WIDTH: 720,
  MIN_TOUCH_TARGET: 44,
  GRID_MIN_CARD_WIDTH: 160,
  GRID_MIN_COLUMNS: 2,
  GRID_MAX_COLUMNS: 4,
  CARD_IMAGE_SIZE: 96,
  HERO_IMAGE_SIZE: 180,
  HERO_BACKDROP_SIZE: 200,
  STATE_ICON_SIZE: 72,
  OFFLINE_BANNER_HEIGHT: 32,
  SKELETON_CARD_COUNT: 6,
  SKELETON_STAT_COUNT: 6,
  STAT_BAR_HEIGHT: 8,
  STAT_LABEL_WIDTH: 84,
  STAT_VALUE_WIDTH: 36,
} as const;

export const POKEBALL_PROPORTIONS = {
  BORDER: 0.06,
  BAND: 0.08,
  BUTTON: 0.32,
  WATERMARK_SCALE: 0.9,
  WATERMARK_OPACITY: 0.08,
} as const;

export const TEXT_SCALE = {
  COMPACT_MAX: 1.3,
} as const;

export const LIST_CONFIG = {
  END_REACHED_THRESHOLD: 0.5,
  INITIAL_NUM_TO_RENDER: 12,
  MAX_TO_RENDER_PER_BATCH: 12,
  WINDOW_SIZE: 7,
} as const;
